export const GET_EVENT_WELCOME_REQUEST = 'GET_EVENT_WELCOME_REQUEST'
export const GET_EVENT_WELCOME_SUCCESS = 'GET_EVENT_WELCOME_SUCCESS'
export const GET_EVENT_WELCOME_FAIL = 'GET_EVENT_WELCOME_FAIL'

export const GET_TEXT_QUERY_REQUEST = 'GET_TEXT_QUERY_REQUEST'
export const GET_TEXT_QUERY_SUCCESS = 'GET_TEXT_QUERY_SUCCESS'
export const GET_TEXT_QUERY_FAIL = 'GET_TEXT_QUERY_FAIL'
export const GET_TEXT_QUERY_RESET = 'GET_TEXT_QUERY_RESET'